traas-stack/holoinsight-agent

pkg/collectconfig/executor/consumer.go
pkg/collectconfig/executor/pipeline.go

Closes #
When running a 5s log monitoring task, data loss will occur.
Here is a concrete example:
time1=40m40s300ms, pull nothing, update estimatedMaxDataTimestamp to '40m40s', update lastFinishedWindow to '40m35s'.
time2=40m45s300ms, pull logs, update estimatedMaxDataTimestamp to maxDataTime '40m41s', update lastFinishedWindow to '40m35s'.
time3=40m50s300ms, pull nothing, update estimatedMaxDataTimestamp to maxDataTime '40m50s', update lastFinishedWindow to '40m45s'.
When time3, lastFinishedWindow jumps from '40m35s' to '40m45s', missing '40m40s'.
The current logic in `pipeline.go` only emit latest window data, discarding data at '40m45s'.
```Golang
if lastFinishedWindow != p.lastEmitWindow {
// We just emit lastFinishedWindow window data.
// If our process hang '10 x window' and …
```

fix: fix 5s log monitoring data loss

---

scripts/build/build-in-container.sh
scripts/build/build-using-docker.sh
scripts/build/detect-goproxy.sh
scripts/docker/Dockerfile
scripts/docker/build.sh
scripts/docker/buildx.sh

Closes #
Supports GOPROXY when building
Supports GOPROXY when building
No
Local test

build: supports GOPROXY when building

---

pkg/appconfig/appconfig.go
pkg/collectconfig/executor/consumer.go
pkg/k8s/k8ssysmetrics/cadvisor/cadvisor.go
pkg/meta/ref_label.go
pkg/meta/ref_label_test.go

Closes #10 
See issue #10 
- Attach tags when emit data
Local test

feat: reflabel

---

scripts/docker/Dockerfile
scripts/docker/build.sh

build: supports building agent bin using local golang

---

scripts/docker/build.sh

build: use latest tag when use local build

---

pkg/collectconfig/executor/consumer.go
pkg/collectconfig/executor/consumer_log_sub_analysis.go
pkg/collectconfig/executor/consumer_log_sub_stat.go
pkg/collectconfig/executor/executor_log.go
pkg/collectconfig/executor/pipeline.go

Closes #
1. Report more log stats that are related to aligned time window
2. The moment of printing the log statistics log is fixed at the first second of every minute. This makes log statistics more stable. 
Local test

refactor: report more log stats

---

cmd/agent/bootstrap.go

chore: add config in bootstrap event

---

pkg/bistream/cmds/inspect/impl.go
pkg/logger/log.go
pkg/pipeline/telegraf/inputs.go
pkg/plugin/input/nvidia_smi/README.md
pkg/plugin/input/nvidia_smi/init.go
pkg/plugin/input/nvidia_smi/nvidia_smi.go

feat: supports gpu metrics

---

scripts/docker/build.sh
scripts/docker/buildx.sh

Closes #
Fix missing gitcommit when build docker image.

fix: fix missing gitcommit when build

---

scripts/docker/Dockerfile

refactor: using mount in Dockerfile to speedup building

---

pkg/collectconfig/executor/consumer_log_sub_analysis.go

Closes #
Fix log analysis naming

fix: fix log analysis naming

---

.github/workflows/build.yaml
.github/workflows/pr-merge-gate.yaml
.pre-commit-config.yaml

Closes #
1. Add commit-message-checker to pr-merge-gate workflow

ci: add commit message checker

---

pkg/appconfig/appconfig.go

Closes #
- Enable k8s 5s-level metrics

refactor: enable k8s 5s-level metrics

---

pkg/pipeline/telegraf/pipeline.go

Closes #
- Supports refLabels for telegraf style pipeline

refactor: supports refLabels for telegraf style pipeline

---

pkg/logger/log.go

refactor: auto build loggers

---

pkg/cri/criutils/copy.go
pkg/cri/criutils/md5sum.go
pkg/cri/criutils/types.go
pkg/cri/impl/default_cri.go
pkg/cri/impl/engine/containerd_engine.go
pkg/cri/impl/engine/docker_engine.go
pkg/cri/model.go
pkg/plugin/input/jvm/input.go
pkg/util/strings.go

Closes #
For some container runtimes, all current methods of copying files fail.
We need other fallback solutions.
- Supports coping file using exec tar

refactor: cri copy

---

pkg/bootstrap/bootstrap.go
pkg/cri/criutils/common.go
pkg/cri/criutils/copy.go
pkg/cri/criutils/types.go
pkg/cri/impl/default_cri.go
pkg/cri/impl/default_cri_http.go
pkg/cri/impl/engine/docker_engine.go
pkg/cri/model.go
pkg/util/context.go
scripts/api/meta/local/hackErrorContainers

Closes #
Supports copy file using 'chunk copy'.
'Chunk copy' splits file into multi chunks, with size <= 90KB.
And then append chunks into container file using `docker exec -e ARG=$chunk ' printenv ARG >> dstFile ' `

feat: chunk copy

---

pkg/k8s/k8ssync/metasync.go

Closes #
Add pod meta sync verbose log

refactor: add pod meta sync verbose log

---

pkg/bootstrap/bootstrap.go
pkg/bootstrap/default.go
pkg/collectconfig/executor/logstream/logstream_file.go
pkg/cri/api.go
pkg/cri/impl/default_cri.go
pkg/cri/impl/metastore.go

Closes #
1. Set the Bootstrap field as public for external access
2. MetaStore supports monitoring changes

refactor: refactor Bootstrap and MetaStore

---

pkg/bistream/cmds/previewlog/impl.go
pkg/collectconfig/executor/logstream/logstream_file.go
pkg/server/registry/registry.go
pkg/util/os_linux.go
pkg/util/os_nolinux.go

fix: fix os.Open in Mac

---

cmd/containerhelper/handlers/tcpproxy.go
cmd/containerhelper/main.go
pkg/cri/api.go
pkg/cri/cricore/nsenter_linux.go
pkg/cri/criutils/tcpproxy.go
pkg/cri/impl/engine/docker_engine.go
pkg/cri/impl/netproxy/port_forward.go
pkg/cri/impl/netproxy/proxy_socks5.go
pkg/cri/impl/network_proxy.go
pkg/logger/log.go
pkg/util/io.go

Closes #
The goroutine for netproxy would hang indefinitely because the associated resource was not closed.
- Carefully close Reader/Writer/Conn after netproxy done

fix: netproxy hang

---

go.mod
go.sum
pkg/collectconfig/executor/elect_pathvar.go
pkg/collectconfig/executor/elect_refname.go
pkg/collectconfig/executor/elect_refname_test.go

Closes #
- RefName supports JsonPath, See https://github.com/oliveagle/jsonpath

refactor: refName supports jsonpath

---

.github/workflows/upload-docker-image.yaml
.github/workflows/upload-release-docker-image.yaml

Closes #
- update docker image using github actions

feat: update docker image using github actions

---

pkg/openmetric/conf.go
pkg/openmetric/openmetric.go
pkg/openmetric/pod_one.go

Closes #
- OpenMetrics supports relabels

refactor: openmetrics supports relabels

---

cmd/plugintest/main.go
cmd/plugintest/telegraf_mysql.json
pkg/model/data.go
pkg/pipeline/integration/base/conf.go
pkg/pipeline/standard/pipeline.go
pkg/plugin/input/standard/telegraf_adapters/mysql/mysql.go
pkg/telegraf/input_adapter.go
pkg/telegraf/memory.go

Closes #
- Support metric value manipulation

feat: support metric value manipulation

---

pkg/appconfig/appconfig.go
pkg/cri/impl/default_cri.go
pkg/cri/impl/metastore.go
pkg/cri/impl/metastore_pod.go
pkg/cri/impl/metastore_pod_informer.go
pkg/cri/impl/metastore_pod_kubelet.go
pkg/cri/impl/netproxy/proxy_http.go
pkg/util/http.go

Closes #
- Get pod meta from kubelet HTTP API. This is a more lightweight way than listening to the apiserver.
-

refactor: get pod meta from kubelet

---

pkg/collectconfig/executor/consumer.go
pkg/collectconfig/executor/logparser.go
pkg/collectconfig/executor/logparser_json.go
pkg/collectconfig/executor/logparser_json_test.go
pkg/collectconfig/executor/logstream/logstream.go
pkg/collecttask/model.go

Closes #
- Fix nil panic when processing sls task

fix: fix sls config

---

pkg/k8s/silence/pod_update_listener.go

Closes #
- Report pod silence to server

feat: report pod silence to server

---

pkg/cri/api.go
pkg/cri/impl/metastore.go
pkg/plugin/input/nvidia_smi/util.go

Closes #
- add `GetPodBySandboxId` for cri.MetaStore
- add utils for nvidia-smi

refactor: pod and gpu

---

pkg/cri/impl/engine/docker_oom_manager.go

Closes #
- Always report OOM events

refactor: always report OOM events

---

pkg/collectconfig/executor/consumer.go
pkg/collectconfig/executor/consumer_log_sub.go
pkg/collectconfig/executor/consumer_log_sub_analysis.go
pkg/collectconfig/executor/consumer_log_sub_detail.go
pkg/collectconfig/executor/consumer_log_sub_stat.go
pkg/collectconfig/executor/consumer_parser.go
pkg/collectconfig/executor/pipeline.go
pkg/collectconfig/type.go
pkg/model/data.go

Closes #
- Supports upload log details to server

feat: supports upload log details to server

---

pkg/collectconfig/executor/transform.go
pkg/collectconfig/executor/transform_cleanurl_v1.go
pkg/collectconfig/executor/transform_test.go
pkg/collectconfig/executor/transforms/cleanurl.yaml
pkg/collectconfig/type_transform.go

Closes #
- Supports cleanurl filter

feat: cleanurl filter

---

pkg/bootstrap/bootstrap.go
pkg/openmetric/dcgm.go
pkg/openmetric/openmetric.go

add dcgm-export metrics collection #84

feat: add dcgm-export metrics collection

---

pkg/openmetric/openmetric.go

fix: modified dcgm job scrape interval

fix: modified dcgm job scrape interval

---

pkg/bistream/cmds/preview_log.go
pkg/collectconfig/executor/consumer.go
pkg/collectconfig/executor/consumer_parser.go
pkg/collectconfig/executor/executor_dryrun.go
pkg/collectconfig/executor/filematch/filematch.go
pkg/collectconfig/executor/filematch/filematch_pod_container.go
pkg/collectconfig/executor/inputsmanager.go
pkg/collectconfig/executor/log_detector.go
pkg/collectconfig/executor/logstream/logstream.go
pkg/collectconfig/executor/logstream/logstream_file.go
pkg/collectconfig/executor/logstream/logstream_g.go
pkg/collectconfig/executor/logstream/logstream_manager.go
pkg/collectconfig/executor/logstream/logstream_reader.go
pkg/collectconfig/executor/pipeline.go
pkg/collectconfig/executor/select.go
pkg/collectconfig/executor/utils/linebuffer.go
pkg/cri/api.go
pkg/cri/dockerutils/consts.go
pkg/cri/dockerutils/jsonlog.go
pkg/cri/impl/default_cri.go
pkg/cri/impl/engine/containerd_engine.go
pkg/cri/impl/engine/docker_engine.go
pkg/cri/model.go
pkg/transfer/manager/manager.go
pkg/util/strings.go
scripts/deploy/build-and-replace-to-pod.sh

Closes #
- Collect logs from container standard output

feat: container stdout

---

pkg/collectconfig/executor/consumer_log_sub_analysis.go
pkg/collectconfig/executor/consumer_log_sub_stat.go
pkg/collectconfig/executor/storage/storage.go
pkg/pipeline/manager.go
scripts/api/pprof/heap
scripts/api/pprof/profile

Closes #
- release memory quickly

fix: release memory quickly

---

go.mod
go.sum
pkg/pipeline/integration/base/conf.go
pkg/pipeline/standard/pipeline.go
pkg/pipeline/standard/script.go
pkg/util/map.go

Closes #
Supports using scripts to modify pipeline execution results.
This function can be used to implement some customized formula-based calculation logic.

feat: supports using scripts to modify pipeline execution results

---

pkg/agent/server/server.go
pkg/collectconfig/type.go
pkg/pipeline/standard/meta.go
pkg/pipeline/standard/pipeline.go

Closes #
- Ref pod meta as data tags

feat: ref meta from pod meta

---

pkg/cri/impl/default_cri.go
pkg/cri/impl/default_cri_http.go
pkg/cri/impl/engine/docker_oom_manager.go
pkg/cri/model.go
pkg/k8s/k8ssysmetrics/cadvisor/cadvisor.go

Closes #
Reduce the original 3 variables to an enumeration value

refactor: container meta

---

pkg/cri/cricore/nsenter.go

fix: fix error

---

cmd/containerhelper/handlers/all.go
cmd/containerhelper/handlers/countThread.go
pkg/plugin/input/all/all.go
pkg/plugin/input/thread/init.go
pkg/plugin/input/thread/input.go

feat: collect pids/threads count

---

pkg/plugin/output/gateway/gateway.go

feat: add configkey in extension

---

pkg/cri/criutils/copy.go

fix: fix copy file failed by tar
