pkg/k8s/k8ssync/metasync.go
Closes #
Succeeded pods now will be sync to server side through `Meta Full Sync`, which can lead to duplicated pod IP in server side.
The current server side's handling of pod IP is not very robust. Duplicated pod IP can lead to many problems.
So let's try to remove succeeded pods, which is a temporary fix.
Remove succeeded pod when meta full sync
No
Local test
=> fix: remove succeeded pods when meta full sync

pkg/collectconfig/executor/consumer.go, pkg/k8s/k8ssync/metasync.go
Closes #
`workspace` is a reserved tag for HoloInsight and is used to separate data from different environments.
Add workspace as a tag of metrics.
=> chore: Add workspace as a tag of metrics

scripts/build/build-using-go.sh
Closes #13 
Disable CGO for containerhelper. So it can run in Alpine based container.
Disable CGO for containerhelper. So it can run in Alpine based container.
No
Local test
=> fix: disable CGO for containerhelper

pkg/k8s/k8smeta/node.go
Closes #
Return nil in `IndexFunc` will lead to panic in k8s internal.
Return empty string when meet broken node to avoid panic.
=> fix: fix k8s panic

pkg/collectconfig/executor/consumer_log_sub_analysis.go
Closes #
rename log analysis metric names:
1. count: old=${prefix}_count, new=${prefix}
2. analysis: old=${prefix}, new=${prefix}_analysis
=> refactor: rename log analysis metric names

pkg/collectconfig/executor/consumer.go, pkg/collectconfig/executor/multiline.go
Closes #
When execute 'beforeParseWhere', we treat whole line group as a string.
So many filters don't need to consider the multiline situation.
=> refactor: multiline filter

pkg/plugin/input/nvidia_smi/nvidia_smi.go
Closes #
Currently, the range of GPU utilization values is [0,100], which needs to be normalized to [0,1].
- normalize GPU utilization
NO
Local test
=> fix: normalize GPU utilization

pkg/bootstrap/default.go, pkg/cri/impl/engine/containerd_engine.go, pkg/cri/impl/engine/docker_engine.go
Closes #
Optimize k8s memory use 
1. Remove usage of "container = &contianers[i]", as this would cause container to refer to the entire containers slice.
2. Add `config = metadata.ConfigFor(config)`, set default contentType to protobuf for better performance than json
=> refactor: optimize k8s memory use

pkg/collectconfig/executor/logstream/logstream_g.go, pkg/collectconfig/executor/pipeline.go
Closes #
Listeners were mistakenly deleted.
The implementations of Listener must not be empty structs.
They will result in same object address when their instances are converted to Listener interface,
which leads to the following 'l!=listener' always returns false
```Golang
func (f *GLogStream) RemoveListener(listener Listener, cursor int64) {
f.Mutex.Lock()
defer f.Mutex.Unlock()
listeners := make([]Listener, 0, len(f.Listeners))
for _, l := range f.Listeners {
// The implementations of Listener must not be empty structs.
// They will result in same object address when their instances are converted to Listener interface,
// which leads to the following 'l!=listener' always returns false
if l != listener {
listeners = append(listeners, l)
}
}
if x := len(f.Listeners) - len(listeners); x > …
```
=> fix: listener deletion

pkg/bootstrap/bootstrap.go
Closes #
The `defaultCri` will start http and socks5 proxy in `Start()` func.
When upgrade holoinsight-agent using lossless mode, the relevant ports are not closed, causing the http and socks5 proxy servers to fail to start.
- Close `cri.Interface` when transfering
=> fix: close cri

pkg/cri/impl/default_cri.go, pkg/cri/model.go
Closes #
- cri.Pod add `Hostname` field
=> refactor: add hostname field

pkg/collectconfig/executor/consumer.go, pkg/collectconfig/executor/logstream/logstream.go, pkg/collectconfig/executor/logstream/logstream_file.go
Closes #
Some files will contain file holes, which will cause us to  produce erroneous data. We have no choice but to discard such log lines.
Discard lines containing \0
=> fix: discard lines containing \0

pkg/cri/containerdutils/containerd_k3s.go, pkg/cri/containerdutils/utils.go, pkg/cri/impl/engine/containerd_engine.go
Closes #
Containerd containers have empty mergedDir. 
- Fix the problem that mergedDir of containerd container is not assigned a value
=> fix: fix containerd mergeddir

cmd/containerhelper/handlers/all.go, cmd/containerhelper/handlers/fixout.go, cmd/containerhelper/handlers/fixout/common.go, cmd/containerhelper/handlers/fixout/decode.go, cmd/containerhelper/handlers/fixout/encode.go, pkg/cri/api.go, pkg/cri/criutils/tcpproxy.go, pkg/cri/impl/default_cri.go, pkg/cri/impl/engine/docker_engine.go, pkg/cri/impl/netproxy/common.go, pkg/cri/impl/netproxy/port_forward.go, pkg/cri/impl/netproxy/proxy_socks5.go, pkg/util/net.go, pkg/util/net_test.go
Closes #
When using the docker exec function, we have no way to perceive the stdout EOF or stderr EOF event of exec. We can only wait until the entire `resp.Reader` EOF before we can consider that both stdout and stderr are EOF. This will cause the connection to hang in some scenarios that rely heavily on the EOF signal.
Add an auxiliary command fixOut, which can execute a child process and re-encode the stdout and stderr of the child process, including the EOF signal.
=> fix: fix docker exec stdout EOF missing

cmd/containerhelper/handlers/tcpproxy.go, pkg/cri/cricore/nsenter_linux.go, pkg/cri/criutils/tcpproxy.go, pkg/cri/impl/netproxy/port_forward.go, pkg/cri/impl/netproxy/proxy_http.go, pkg/cri/impl/netproxy/proxy_socks5.go, pkg/util/net.go
=> refactor: refactor tcpproxy

pkg/cri/impl/engine/containerd_engine.go, pkg/cri/impl/engine/docker_engine.go, pkg/cri/impl/engine/utils.go
Closes #
The target process may hang and not exit for any reason.  
We encountered this in practice. I guessed some reasons, but it was difficult to reproduce stably.
- `wrapTimeout` wraps cmd with `timeout -s KILL <seconds>` to prevent the process from hanging and not exiting for any reason.
- `wrapEnv` wraps envs with `_FROM=holoinsight-agent`. This env is used to mark the source of the call.
=> fix: wrap exec with timeout and _FROM env

cmd/containerhelper/handlers/all.go, cmd/containerhelper/handlers/countZombies.go, cmd/containerhelper/handlers/countZombies.sh, cmd/containerhelper/main.go, pkg/core/helper.go, pkg/cri/criutils/zombies.go, pkg/cri/impl/default_cri.go, pkg/cri/impl/engine/containerd_engine.go, pkg/cri/impl/engine/docker_engine.go, pkg/cri/impl/engine/utils.go, pkg/cri/model.go, pkg/plugin/output/gateway/consumer.go, pkg/plugin/output/gateway/service.go
Closes #
- Do not execute the timeout command, it will generate zombie processes
=> fix: timeout zombie processes in alpine based containers

cmd/containerhelper/handlers/countZombies.go, pkg/cri/api.go, pkg/cri/criutils/copy.go, pkg/cri/impl/default_cri.go, pkg/cri/impl/default_cri_http.go, pkg/cri/impl/engine/containerd_engine.go, pkg/cri/impl/engine/docker_engine.go, pkg/cri/impl/engine/utils.go, pkg/cri/impl/metastore.go, pkg/cri/impl/netproxy/port_forward.go, pkg/cri/impl/netproxy/proxy_socks5.go, pkg/cri/model.go
Closes #
We previously used timeout to wrap the command to be executed to prevent the command from hanging and not exiting due to various reasons.
However, it was found that in Alpine-based containers, if process 1 does not have the ability to recycle zombie processes, timeout will cause zombie processes to be generated.
Eventually causing the container to OOM.
Therefore, we need to add detection logic and use timeout to wrap the command to be executed only when ensuring that the target container has the ability to recycle zombie processes.
=> fix: fix docker exec zombies

pkg/collectconfig/executor/inputsmanager.go, pkg/collectconfig/executor/logstream/logstream_g.go, pkg/collectconfig/executor/logstream/logstream_manager.go, pkg/cri/impl/default_cri.go
Closes #
fix logstream state error when target file is a docker log
=> fix: fix logstream state

pkg/cri/impl/engine/containerd_engine.go
Closes #
According to actual measurements, spec.mounts is different from containerMeta.Config.Mounts.  
It's better to use spec.mounts.
=> fix: fix containerd mounts

pkg/collectconfig/executor/consumer_log_sub_detail.go, pkg/collectconfig/executor/log-to-sls.json, pkg/collectconfig/type.go, pkg/pipeline/standard/outputs.go, pkg/pipeline/standard/parse.go, pkg/plugin/input/thread/input.go, pkg/plugin/output/all/all.go, pkg/plugin/output/gateway/gateway.go, pkg/plugin/output/output.go, pkg/plugin/output/sls/init.go, pkg/plugin/output/sls/sls.go
=> feat: detail log write to sls
